//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitGraphicsOverride {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitGraphicsOverride.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overriden elements are not found!.
        /// </summary>
        public static string ErrorNoElements {
            get {
                return ResourceManager.GetString("ErrorNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halftones.
        /// </summary>
        public static string Halftones {
            get {
                return ResourceManager.GetString("Halftones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection line color.
        /// </summary>
        public static string ProjectionLineColor {
            get {
                return ResourceManager.GetString("ProjectionLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection line pattern.
        /// </summary>
        public static string ProjectionLinePattern {
            get {
                return ResourceManager.GetString("ProjectionLinePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection line weight.
        /// </summary>
        public static string ProjectionLineThickness {
            get {
                return ResourceManager.GetString("ProjectionLineThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section background hatch color.
        /// </summary>
        public static string SectionBackgroundHatchColor {
            get {
                return ResourceManager.GetString("SectionBackgroundHatchColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section background hatch disable.
        /// </summary>
        public static string SectionBackgroundHatchDisable {
            get {
                return ResourceManager.GetString("SectionBackgroundHatchDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section background hatch pattern.
        /// </summary>
        public static string SectionBackgroundHatchPattern {
            get {
                return ResourceManager.GetString("SectionBackgroundHatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section foreground hatch color.
        /// </summary>
        public static string SectionForegroundHatchColor {
            get {
                return ResourceManager.GetString("SectionForegroundHatchColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section foreground hatch disable.
        /// </summary>
        public static string SectionForegroundHatchDisable {
            get {
                return ResourceManager.GetString("SectionForegroundHatchDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section foreground hatch pattern.
        /// </summary>
        public static string SectionForegroundHatchPattern {
            get {
                return ResourceManager.GetString("SectionForegroundHatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section hatch color.
        /// </summary>
        public static string SectionHatchColor {
            get {
                return ResourceManager.GetString("SectionHatchColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section hatch disable.
        /// </summary>
        public static string SectionHatchDisable {
            get {
                return ResourceManager.GetString("SectionHatchDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section hatch pattern.
        /// </summary>
        public static string SectionHatchPattern {
            get {
                return ResourceManager.GetString("SectionHatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section line color.
        /// </summary>
        public static string SectionLineColor {
            get {
                return ResourceManager.GetString("SectionLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section line pattern.
        /// </summary>
        public static string SectionLinePattern {
            get {
                return ResourceManager.GetString("SectionLinePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section line weight.
        /// </summary>
        public static string SectionLineThickness {
            get {
                return ResourceManager.GetString("SectionLineThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        public static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface background hatch color.
        /// </summary>
        public static string SurfaceBackgroundHatchColor {
            get {
                return ResourceManager.GetString("SurfaceBackgroundHatchColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface background hatch disable.
        /// </summary>
        public static string SurfaceBackgroundHatchDisable {
            get {
                return ResourceManager.GetString("SurfaceBackgroundHatchDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface background hatch pattern.
        /// </summary>
        public static string SurfaceBackgroundHatchPattern {
            get {
                return ResourceManager.GetString("SurfaceBackgroundHatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface foreground hatch color.
        /// </summary>
        public static string SurfaceForegroundHatchColor {
            get {
                return ResourceManager.GetString("SurfaceForegroundHatchColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface foreground hatch disable.
        /// </summary>
        public static string SurfaceForegroundHatchDisable {
            get {
                return ResourceManager.GetString("SurfaceForegroundHatchDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface foreground hatch pattern.
        /// </summary>
        public static string SurfaceForegroundHatchPattern {
            get {
                return ResourceManager.GetString("SurfaceForegroundHatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface hatch color.
        /// </summary>
        public static string SurfaceHatchColor {
            get {
                return ResourceManager.GetString("SurfaceHatchColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface hatch disable.
        /// </summary>
        public static string SurfaceHatchDisable {
            get {
                return ResourceManager.GetString("SurfaceHatchDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface hatch pattern.
        /// </summary>
        public static string SurfaceHatchPattern {
            get {
                return ResourceManager.GetString("SurfaceHatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
    }
}
